### ISSUE TITLE
MetaWare Lite Development Toolkit

### ISSUE THREAD

**Issue by abdullahyildiz** [foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum#2]
Where to download the toolkit?

**Comment by wengqy** [comment]
I installed the DesignWare ARC MetaWare Lite,and a error happened during Activation, I enter the right code that I recived from the registation email. if any one konw how to solve this problem ,please tell me ,thank you so much, I waste lot of time at this Problem, so disapoint, if any one have any ideal,you can send me a email weng_qy@163.com,thank you!!

**Comment by jcampbel** [comment]
Hello,
Are you trying to activate this from a home network or an office environment?
We have had issues where the activation fails due to firewalls (this has happened more than average from China)
As a first step, I’d recommend trying to do the activation from a different network to see if that makes any difference.
Meanwhile, can you please send a screenshot of the failure?

Thank you
Jamie
ARC CAE team

**Comment by wengqy** [comment]
Hello,
     thank you for you reply,I activate from an office environment,and yes this email is come from china.
Thank you!





At 2017-01-07 11:33:53, "jcampbel" <notifications@github.com> wrote:
Hello,
Are you trying to activate this from a home network or an office environment?
We have had issues where the activation fails due to firewalls (this has happened more than average from China)
As a first step, I’d recommend trying to do the activation from a different network to see if that makes any difference.
Meanwhile, can you please send a screenshot of the failure?

Thank you
Jamie
ARC CAE team

**Comment by wengqy** [comment]
Hello,
      I activate at a PC ,not a notebook, so is not convenience to activation from a different network . One of my colleague is activate successed,We share one IP,is this will make me activate error? my english is so poor, i hope you can understand what i mean. thank you!





At 2017-01-07 11:33:53, "jcampbel" <notifications@github.com> wrote:
Hello,
Are you trying to activate this from a home network or an office environment?
We have had issues where the activation fails due to firewalls (this has happened more than average from China)
As a first step, I’d recommend trying to do the activation from a different network to see if that makes any difference.
Meanwhile, can you please send a screenshot of the failure?

Thank you
Jamie
ARC CAE team

**Comment by wengqy** [comment]
![sdk_problem](https://cloud.githubusercontent.com/assets/24969601/21739819/acb6150c-d4e1-11e6-8c98-cc7507fed5eb.png)

**Comment by ElliotCheng** [comment]
hi wengqy,
   Metaware lite on windows need to have .net4.5 and opennetwork to connect to its activation server. You could check your program and features to see if you've installed .Net4.5. Below is the download page:
https://www.microsoft.com/en-us/download/details.aspx?id=30653
  If your internet forbids the connection you wil also see such activation errors. Please try and let us know, thanks.
-Elliot
ARC Techinical Support Team

**Comment by wengqy** [comment]
@ElliotCheng  Thank you So much~ the problem is solved. I installed .net4.5. thank you

**Comment by ElliotCheng** [comment]
@wengqy Glad to know, and have fun:)
