### ISSUE TITLE
Cannot uninstall MW Lite 1.0

### ISSUE THREAD

**Issue by abdullahyildiz** [foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum#8]
During uninstall, it gives the following error:

![image](https://cloud.githubusercontent.com/assets/3716793/6571944/74cbc05e-c716-11e4-9abc-acc0ffeb4f22.png)

I use Windows 7 64-bit and have JRE installed.

**Comment by ElliotCheng** [comment]
Hi Abdullahyildiz, we have new release for MW Lite J-2014.12, please register on the following webpage "http://www.synopsys.com/cgi-bin/arcmwtk_lite/reg1.cgi" and get a license for it after approval. Your problem comes from JDK upgrade, you could try the following before applying for a  new version of MW Lite:
1 go to C:\MWLite\Uninstall DesignWare ARC MetaWare Lite (where you install MW Lite), find the file named Uninstall DesignWare ARC MetaWare Lite.lax
2 find the following line:
#   LAX.NL.CURRENT.VM
#   -----------------
#   the VM to use for the next launch

lax.nl.current.vm=
3 make this variable point to a valid jre value, here's what I have on my machine: 
lax.nl.current.vm=..\\javaruntime\\bin\\java.exe

  Then you could uninstall as epxected. Please let me know if it applies on your machine, thanks.

**Comment by abdullahyildiz** [comment]
Thank you. It worked.
